name: my_gym_oficial
description: "App para gestionar usuario y sus pagos en un gimnasio."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  data_table_2: ^2.6.0
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  sqflite: ^2.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/imagenes/fondo_scaffold.webp
